### ISSUE TITLE
Programmer to use and substitute 3.3uf caps

### ISSUE THREAD

**Issue by mamejay** [desaster/c64-dodgypla#2]
Hello there.  I know  this is probably a silly question.  This is my first time working with Xilinx chips.
I have experience with Arduino etc.
I am looking to get a generic JTAG cable which is stated to be compatible with the Xilinx ISE.
https://www.ebay.com.au/itm/262136736614

Lastly can I substitute the 3.3uf caps with another value?  I am just finding that they are not too common in Australia.  
Thanks

**Comment by desaster** [comment]
Personally, I don't have a proper jtag cable for xilinx, and I'm using bus blaster instead. The programmer you linked would be a better choice, but I have no experience with it so I can't tell if it works.

You can certainly substitute the caps for something else. I don't remember why I have 3.3uF caps there, since I'm probably using something else myself. They're probably from some reference design.

Looking at reference designs for voltage regulators, there's a wide range of different values used. I might just go with anything between 1uF and 10uF. To pick "proper" values, you'd have to ask someone else :)

EDIT: also don't worry about the voltage voltage regulator part number too much. I have a bunch of parts labeled AMS1117 from china, but you could substitute it with LM1117 or any compatible 3v3 regulator.

**Comment by mamejay** [comment]
Thank so much for that.  I have a heap of LM1117's so will use one of these with 1uf caps.  Hopefully I manage to perform the programming once I get the programmer

**Comment by mamejay** [comment]
Finally got some built.  All working perfectly.  Thank you for your help
